# Generated by Django 3.1.4 on 2021-01-26 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210126_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
