# Generated by Django 3.1.4 on 2021-01-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210126_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followed',
            new_name='following',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
